name: MoLing Release
on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-on-ubuntu2204:
    strategy:
      matrix:
        os: [ darwin, windows, linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-22.04
    name: test on ${{ matrix.os }} ${{ matrix.arch }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Generate Release Notes
        id: release_notes
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name=${{ github.ref_name }} \
            -f previous_tag_name=${{ steps.previoustag.outputs.PREVIOUS_TAG }} \
            > release_notes.json
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          jq -r .body release_notes.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ./bin/release_notes.txt
          contents: |
            ${{ steps.release_notes.outputs.NOTES }}
          write-mode: append
      - name: MoLing Build
        run: |
          make clean
          TARGET_OS=${{ matrix.os }} TARGET_ARCH=${{ matrix.arch }} make env
          TARGET_OS=${{ matrix.os }} TARGET_ARCH=${{ matrix.arch }} make build
          pwd
          ls -al ./bin
      - name: Create Archive
        run: |
          mkdir -p ./dist
          pwd
          ls -al ./bin
          if [ "${{ matrix.os }}" = "windows" ]; then
            cd ./bin && zip -qr ./../dist/moling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.zip ./bin/ . && cd ..
          else
            tar -czvf dist/moling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C ./bin/ .
          fi
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
            tag_name: ${{ github.ref_name }}
            release_name: ${{ github.ref_name }}
            files: |
                ./dist/moling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.*